apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-pod
  namespace: test-init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      run: myapp
  template:
    metadata:
      labels:
        run: myapp

    spec:
      containers:
        - name: myapp-container
          image: busybox:1.28
          command: [ 'sh', '-c', 'sleep 120 && echo The app is running! && sleep 3600' ]
      initContainers:
        - name: init-myservice
          image: <IMAGE_URL>
          args: [ "1.2.3" ]
      serviceAccountName: <K8s_SERVICE_USER_NAME>
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
